name: Build 1.20.1

on: [ push, pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-write-only: false

      - name: Build with Gradle
        run: ./gradlew build --no-daemon

      - name: Run Tests
        run: ./gradlew test --no-daemon

      - name: Create timestamp for snapshot
        if: github.event_name == 'push'
        id: timestamp
        run: echo "timestamp=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

      - name: Publish Snapshot to GitHub Releases
        if: github.event_name == 'push'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: snapshot-${{ steps.timestamp.outputs.timestamp }}
          name: Snapshot Build ${{ steps.timestamp.outputs.timestamp }}
          body: |
            Automatic snapshot build triggered by commit: ${{ github.sha }}
            Commit message: ${{ github.event.head_commit.message }}
          draft: false
          prerelease: true
          files: |
            build/libs/*.jar
          generate_release_notes: true

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-outputs
          path: |
            build/libs/
            build/reports/
          retention-days: 7
